### ISSUE TITLE
Requests push perms for search-engine

### ISSUE THREAD

**Issue by potetm** [NashFP/search-engine#1]
Hey ya'll!

Can I get push perms please?

Most Sincerely,

Tim

**Comment by jorendorff** [comment]
@bryanhunter @digitalBush @drewr @wilkes Hello team! Would you please add @potetm to the organization? I can vouch for him (in case any of you haven't met Tim -- I think all of you have, but I"m not sure).

**Comment by digitalBush** [comment]
@potetm You should have an invite!

**Comment by drewr** [comment]
Wilkommen @potetm!

And I love this project idea! :heart:
